package com.sx_report.model;

import java.math.BigDecimal;
import java.util.Date;

public class SEC_USER {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_USER.SID
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    private BigDecimal sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_USER.ACCOUNTNAME
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    private String accountname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_USER.PASSWORD
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_USER.SIDPARENT
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    private BigDecimal sidparent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_USER.CONFIGID
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    private BigDecimal configid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_USER.DEPTTYPE
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    private BigDecimal depttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_USER.FLAGS
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    private BigDecimal flags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_USER.NAME
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_USER.ADDRESS
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_USER.EMAILADDRESS
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    private String emailaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_USER.TELEPHONE
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEC_USER.MOBILE
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    private String mobile;

    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_USER.SID
     *
     * @return the value of SEC_USER.SID
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public BigDecimal getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_USER.SID
     *
     * @param sid the value for SEC_USER.SID
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public void setSid(BigDecimal sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_USER.ACCOUNTNAME
     *
     * @return the value of SEC_USER.ACCOUNTNAME
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public String getAccountname() {
        return accountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_USER.ACCOUNTNAME
     *
     * @param accountname the value for SEC_USER.ACCOUNTNAME
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public void setAccountname(String accountname) {
        this.accountname = accountname == null ? null : accountname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_USER.PASSWORD
     *
     * @return the value of SEC_USER.PASSWORD
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_USER.PASSWORD
     *
     * @param password the value for SEC_USER.PASSWORD
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_USER.SIDPARENT
     *
     * @return the value of SEC_USER.SIDPARENT
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public BigDecimal getSidparent() {
        return sidparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_USER.SIDPARENT
     *
     * @param sidparent the value for SEC_USER.SIDPARENT
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public void setSidparent(BigDecimal sidparent) {
        this.sidparent = sidparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_USER.CONFIGID
     *
     * @return the value of SEC_USER.CONFIGID
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public BigDecimal getConfigid() {
        return configid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_USER.CONFIGID
     *
     * @param configid the value for SEC_USER.CONFIGID
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public void setConfigid(BigDecimal configid) {
        this.configid = configid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_USER.DEPTTYPE
     *
     * @return the value of SEC_USER.DEPTTYPE
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public BigDecimal getDepttype() {
        return depttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_USER.DEPTTYPE
     *
     * @param depttype the value for SEC_USER.DEPTTYPE
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public void setDepttype(BigDecimal depttype) {
        this.depttype = depttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_USER.FLAGS
     *
     * @return the value of SEC_USER.FLAGS
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public BigDecimal getFlags() {
        return flags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_USER.FLAGS
     *
     * @param flags the value for SEC_USER.FLAGS
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public void setFlags(BigDecimal flags) {
        this.flags = flags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_USER.NAME
     *
     * @return the value of SEC_USER.NAME
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_USER.NAME
     *
     * @param name the value for SEC_USER.NAME
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_USER.ADDRESS
     *
     * @return the value of SEC_USER.ADDRESS
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_USER.ADDRESS
     *
     * @param address the value for SEC_USER.ADDRESS
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_USER.EMAILADDRESS
     *
     * @return the value of SEC_USER.EMAILADDRESS
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public String getEmailaddress() {
        return emailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_USER.EMAILADDRESS
     *
     * @param emailaddress the value for SEC_USER.EMAILADDRESS
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public void setEmailaddress(String emailaddress) {
        this.emailaddress = emailaddress == null ? null : emailaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_USER.TELEPHONE
     *
     * @return the value of SEC_USER.TELEPHONE
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_USER.TELEPHONE
     *
     * @param telephone the value for SEC_USER.TELEPHONE
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEC_USER.MOBILE
     *
     * @return the value of SEC_USER.MOBILE
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEC_USER.MOBILE
     *
     * @param mobile the value for SEC_USER.MOBILE
     *
     * @mbggenerated Fri Oct 14 11:14:37 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

   
}